name: github-actions
on: workflow_dispatch
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from github
        run: |
          git clone https://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@github.com/LiweiChen1/techscrum
      # - name: Build App
      #   run: |
      #     cd techscrum
      #     yarn install
      #     yarn run build
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ vars.AWS_REGION_AU }}
      # - name: show current directory
      #   run: |
      #     pwd
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test
  deploy-to-s3:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [build-on-linux]
    steps:
      - name: List S3 buckets (Debug)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION_AU }}
        run: aws s3 ls --debug
