name: github-actions
on: workflow_dispatch
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from github
        run: |
          git clone https://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@github.com/LiweiChen1/techscrum
      - name: Build App
        run: |
          yarn install
          yarn run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy
