name: github-actions
on: workflow_dispatch
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from github
        run: |
          git clone https://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@github.com/LiweiChen1/techscrum
      - name: Build App
        run: |
          cd techscrum
          yarn install
          yarn run build
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-2
      - name: show current directory
        run: |
          pwd
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test
  deploy-to-s3:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [build-on-linux]
    steps:
     - name: deploy to s3
       run: |
          aws s3 sync ./build/* s3://yuri-bucket/v1.0.0/
